import React from 'react'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import { useRouter} from 'next/router'

function dm() {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>
    </div>
  )
}

export default dm